version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: backend
    environment:
      - ENV_FILE=.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
